language: php
php:
  - 7.0
  - hhvm
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
env:
  global:
    - CC_TEST_REPORTER_ID=55c94a6d98194c030ecbdfda52c4b51bf2c330b3618a7fe2a1a4dcdfcd58ae4d
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - cd ./src/Ramble
  - ./build.sh --ci
script:
  - ./vendor/bin/phpunit -c phpunit.xml
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
