version: '3'
services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker-conf/nginx/nginx.docker.conf:/etc/nginx/conf.d/default.conf
      - ./src/Ramble/logs/nginx:/var/logs/nginx
    depends_on:
      - php
      - db
  php:
    container_name: rambleblog_php_1
    image: sacredskull/php-7-fpm-development:latest
    volumes:
      - .:/var/www
      - ./src/Ramble/logs/php:/var/log/php
      - ./docker-conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9001:9000"
      - "2020:2020"
      - "9089:9089"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
  db:
    image: mariadb
    volumes:
      - mysqldatabase:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog
      - MYSQL_PASSWORD=sacredskullBlog
      - TERM=xterm
  ssh:
    image: jeroenpeeters/docker-ssh
    ports:
      - "2222:22"
      - "8022:8022"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINER=rambleblog_php_1
      - AUTH_MECHANISM=noAuth
      - AUTH_USER=docker
      - AUTH_PASSWORD=docker
    depends_on:
      - php
  blackfire:
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_CLIENT_ID=e29d8012-566e-41ed-b5c0-2cb5e121e5f4
      - BLACKFIRE_CLIENT_TOKEN=f1f0ad61e0d47bc55d79be88f475c078ab6e2db020f20b817f429fedca92b240
      - BLACKFIRE_SERVER_ID=ec42f582-14cf-4955-b79a-ebbb79930c32
      - BLACKFIRE_SERVER_TOKEN=eabc7b1f546451e4c222167e8f6dc812e833f60a5c4e35a5067750ea4d4ddb98
volumes:
  mysqldatabase:
