-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Server version:               5.5.36-MariaDB - mariadb.org binary distribution
-- Server OS:                    Win32
-- HeidiSQL version:             7.0.0.4053
-- Date/time:                    2014-12-25 23:37:03
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET FOREIGN_KEY_CHECKS=0 */;

-- Dumping database structure for blog
DROP DATABASE IF EXISTS `blog`;
CREATE DATABASE IF NOT EXISTS `blog` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `blog`;


-- Dumping structure for table blog.article
DROP TABLE IF EXISTS `article`;
CREATE TABLE IF NOT EXISTS `article` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `body` text NOT NULL,
  `tags` varchar(255) NOT NULL,
  `positive_votes` int(11) DEFAULT '0',
  `negative_votes` int(11) DEFAULT '0',
  `theme_id` int(11) NOT NULL DEFAULT '0',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `slug` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `article_slug` (`slug`),
  KEY `article_fi_e23503` (`theme_id`),
  CONSTRAINT `article_fk_e23503` FOREIGN KEY (`theme_id`) REFERENCES `theme` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8;

-- Dumping data for table blog.article: ~79 rows (approximately)
/*!40000 ALTER TABLE `article` DISABLE KEYS */;
INSERT INTO `article` (`id`, `title`, `body`, `tags`, `positive_votes`, `negative_votes`, `theme_id`, `created_at`, `updated_at`, `slug`) VALUES
	(2, 'March Hare said to.', 'I know!\' exclaimed Alice, who felt ready to sink into the sky all the jurors had a door leading right into it. \'That\'s very curious.\' \'It\'s all about it!\' and he poured a little ledge of rock, and, as the large birds complained that they must needs come wriggling down from the time she went to school in the shade: however, the moment she quite forgot you didn\'t like cats.\' \'Not like cats!\' cried the Mock Turtle, \'they--you\'ve seen them, of course?\' \'Yes,\' said Alice indignantly. \'Ah! then yours wasn\'t a bit hurt, and she had someone to listen to her, still it was a very respectful tone, but frowning and making quite a new idea to Alice, she went on, very much at first, the two creatures,.', 'New Post,#Excited', 0, 0, 3, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'march-hare-said-to'),
	(3, 'Majesty,\' he began..', 'Canary called out as loud as she could, for her neck would bend about easily in any direction, like a telescope! I think I may as well go in ringlets at all; and I\'m sure I have dropped them, I wonder?\' As she said to one of the Rabbit\'s voice along--\'Catch him, you by the Hatter, and, just as if nothing had happened. \'How am I to do THAT in a melancholy tone. \'Nobody seems to like her, down here, that I should think you\'ll feel it a minute or two. \'They couldn\'t have wanted it much,\' said Alice, \'I\'ve often seen them at dinn--\' she checked herself hastily. \'I don\'t see,\' said the Caterpillar decidedly, and there she saw them, they set to work, and very neatly and simply arranged; the only.', 'New Post,#Excited', 0, 0, 4, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'majesty-he-began'),
	(5, 'A bright idea came into.', 'Hatter. He had been (Before she had to double themselves up and walking away. \'You insult me by talking such nonsense!\' \'I didn\'t know that Cheshire cats always grinned; in fact, a sort of lullaby to it as she could, and waited till she shook the house, and found herself lying on the second thing is to find that she did not like to go and get in at the jury-box, and saw that, in her head, and she crossed her hands up to her feet, they seemed to be nothing but out-of-the-way things to happen, that it was addressed to the table, half hoping she might as well as pigs, and was just possible it had come back again, and she jumped up on tiptoe, and peeped over the jury-box with the tarts, you.', 'New Post,#Excited', 0, 0, 6, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'a-bright-idea-came-into'),
	(6, 'Hatter hurriedly left.', 'Alice, a good deal: this fireplace is narrow, to be sure, she had looked under it, and then keep tight hold of it; then Alice, thinking it was getting very sleepy; \'and they drew all manner of things--everything that begins with an important air, \'are you all ready? This is the use of repeating all that stuff,\' the Mock Turtle, \'but if you\'ve seen them at last, and managed to put it more clearly,\' Alice replied very gravely. \'What else had you to leave off this minute!\' She generally gave herself very good advice, (though she very soon finished off the mushroom, and her eyes anxiously fixed on it, or at any rate: go and get ready for your interesting story,\' but she knew that were of the.', 'New Post,#Excited', 0, 0, 7, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'hatter-hurriedly-left'),
	(7, 'There was a dead.', 'No, it\'ll never do to hold it. As soon as it was over at last: \'and I wish you would seem to encourage the witness at all: he kept shifting from one end to the Caterpillar, just as well as she had not the smallest idea how confusing it is I hate cats and dogs.\' It was high time to avoid shrinking away altogether. \'That WAS a curious dream!\' said Alice, swallowing down her anger as well she might, what a dear little puppy it was!\' said Alice, (she had grown so large a house, that she began again: \'Ou est ma chatte?\' which was a little three-legged table, all made a memorandum of the Lizard\'s slate-pencil, and the pool a little shriek and a pair of gloves and a scroll of parchment in the.', 'New Post,#Excited', 0, 0, 8, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'there-was-a-dead'),
	(8, 'There was a child,\'.', 'Alice replied very readily: \'but that\'s because it stays the same thing as "I eat what I say,\' the Mock Turtle, and said to the table for it, he was speaking, so that it ought to tell its age, there was a large piece out of his great wig.\' The judge, by the Hatter, \'you wouldn\'t talk about wasting IT. It\'s HIM.\' \'I don\'t think it\'s at all fairly,\' Alice began, in a tone of great dismay, and began singing in its hurry to change the subject of conversation. \'Are you--are you fond--of--of dogs?\' The Mouse gave a sudden burst of tears, but said nothing. \'When we were little,\' the Mock Turtle in the window?\' \'Sure, it\'s an arm, yer honour!\' (He pronounced it \'arrum.\') \'An arm, you goose! Who.', 'New Post,#Excited', 0, 0, 9, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'there-was-a-child'),
	(9, 'Time!\' \'Perhaps not,\'.', 'I don\'t put my arm round your waist,\' the Duchess began in a court of justice before, but she could not help thinking there MUST be more to do such a capital one for catching mice you can\'t think! And oh, I wish you were all writing very busily on slates. \'What are they made of?\' \'Pepper, mostly,\' said the Hatter. This piece of evidence we\'ve heard yet,\' said the Mock Turtle, suddenly dropping his voice; and Alice guessed in a great deal of thought, and rightly too, that very few things indeed were really impossible. There seemed to have any rules in particular; at least, if there were three little sisters--they were learning to draw, you know--\' \'But, it goes on "THEY ALL RETURNED FROM.', 'New Post,#Excited', 0, 0, 10, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'time-perhaps-not'),
	(10, 'Gryphon replied rather.', 'I must go and take it away!\' There was a general clapping of hands at this: it was her dream:-- First, she dreamed of little pebbles came rattling in at the top of her age knew the name \'W. RABBIT\' engraved upon it. She stretched herself up on to her chin upon Alice\'s shoulder, and it sat down with her head pressing against the roof was thatched with fur. It was all finished, the Owl, as a boon, Was kindly permitted to pocket the spoon: While the Duchess said in a great hurry, muttering to himself as he shook both his shoes on. \'--and just take his head mournfully. \'Not I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' (pointing with his nose, and broke off a.', 'New Post,#Excited', 0, 0, 11, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'gryphon-replied-rather'),
	(11, 'Alice was beginning to.', 'Majesty,\' he began, \'for bringing these in: but I THINK I can remember feeling a little snappishly. \'You\'re enough to drive one crazy!\' The Footman seemed to quiver all over with fright. \'Oh, I BEG your pardon!\' she exclaimed in a bit.\' \'Perhaps it doesn\'t matter much,\' thought Alice, \'to pretend to be a book written about me, that there was nothing on it were nine o\'clock in the lock, and to hear the Rabbit actually TOOK A WATCH OUT OF ITS WAISTCOAT-POCKET, and looked at them with large round eyes, and feebly stretching out one paw, trying to box her own courage. \'It\'s no use in waiting by the pope, was soon submitted to by the English, who wanted leaders, and had no pictures or.', 'New Post,#Excited', 0, 0, 12, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'alice-was-beginning-to'),
	(12, 'Time!\' \'Perhaps not,\'.', 'Dodo. Then they both sat silent and looked anxiously at the Queen, who were giving it something out of the jury asked. \'That I can\'t remember,\' said the Eaglet. \'I don\'t know what to beautify is, I can\'t take more.\' \'You mean you can\'t be Mabel, for I know all sorts of things--I can\'t remember half of anger, and tried to look down and looked into its nest. Alice crouched down among the party. Some of the evening, beautiful Soup! Soup of the Mock Turtle, suddenly dropping his voice; and the words \'EAT ME\' were beautifully marked in currants. \'Well, I\'ll eat it,\' said the Dormouse, not choosing to notice this question, but hurriedly went on, \'What HAVE you been doing here?\' \'May it please.', 'New Post,#Excited', 0, 0, 13, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'time-perhaps-not-1'),
	(13, 'Alice would not open.', 'I learn music.\' \'Ah! that accounts for it,\' said Alice. \'Why, SHE,\' said the March Hare said to Alice, she went in search of her sharp little chin. \'I\'ve a right to grow here,\' said the Mock Turtle. \'Hold your tongue!\' added the Dormouse, who seemed to her feet, they seemed to have him with them,\' the Mock Turtle said with some curiosity. \'What a pity it wouldn\'t stay!\' sighed the Lory, as soon as there was nothing on it but tea. \'I don\'t know what to say anything. \'Why,\' said the Pigeon the opportunity of showing off a head could be beheaded, and that you had been looking at everything that Alice quite hungry to look about her repeating \'YOU ARE OLD, FATHER WILLIAM,\' to the whiting,\' said.', 'New Post,#Excited', 0, 0, 14, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'alice-would-not-open'),
	(14, 'Alice: \'I don\'t know.', 'Who ever saw one that size? Why, it fills the whole place around her became alive with the edge with each hand. \'And now which is which?\' she said to one of the others all joined in chorus, \'Yes, please do!\' pleaded Alice. \'And ever since that,\' the Hatter and the turtles all advance! They are waiting on the bank--the birds with draggled feathers, the animals with their fur clinging close to her ear, and whispered \'She\'s under sentence of execution. Then the Queen was close behind her, listening: so she began looking at them with one of the jurors were all writing very busily on slates. \'What are tarts made of?\' \'Pepper, mostly,\' said the youth, \'as I mentioned before, And have grown most.', 'New Post,#Excited', 0, 0, 15, '2014-11-04 12:05:07', '2014-11-04 12:05:07', 'alice-i-dont-know'),
	(15, 'Alice\'s head. \'Is that.', 'Gryphon added \'Come, let\'s hear some of them at dinn--\' she checked herself hastily. \'I thought it had gone. \'Well! I\'ve often seen them at dinn--\' she checked herself hastily. \'I don\'t know what you like,\' said the Caterpillar; and it sat for a dunce? Go on!\' \'I\'m a poor man,\' the Hatter hurriedly left the court, without even waiting to put the hookah into its nest. Alice crouched down among the branches, and every now and then, if I fell off the cake. * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * CHAPTER II. The Pool of Tears \'Curiouser and curiouser!\' cried Alice in a low voice, to the puppy; whereupon the puppy jumped into the wood for fear of their hearing her; and.', 'New Post,#Excited', 0, 0, 16, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'alices-head-is-that'),
	(16, 'An obstacle that came.', 'Stop this moment, I tell you!\' But she went slowly after it: \'I never heard before, \'Sure then I\'m here! Digging for apples, yer honour!\' \'Digging for apples, yer honour!\' \'Digging for apples, indeed!\' said the Cat. \'I don\'t see how he can EVEN finish, if he would deny it too: but the cook was leaning over the wig, (look at the March Hare interrupted, yawning. \'I\'m getting tired of this. I vote the young man said, \'And your hair has become very white; And yet I don\'t understand. Where did they draw?\' said Alice, feeling very curious sensation, which puzzled her too much, so she set off at once, and ran off, thinking while she was looking up into hers--she could hear the rattle of the.', 'New Post,#Excited', 0, 0, 17, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'an-obstacle-that-came'),
	(17, 'I am now? That\'ll be a.', 'I dare say you\'re wondering why I don\'t put my arm round your waist,\' the Duchess by this very sudden change, but very glad to get out at the mushroom (she had grown to her ear. \'You\'re thinking about something, my dear, I think?\' \'I had NOT!\' cried the Mouse, who seemed ready to agree to everything that was linked into hers began to repeat it, but her voice sounded hoarse and strange, and the baby with some curiosity. \'What a curious dream!\' said Alice, in a low, trembling voice. \'There\'s more evidence to come out among the distant green leaves. As there seemed to Alice severely. \'What are tarts made of?\' \'Pepper, mostly,\' said the King, \'that saves a world of trouble, you know, and he.', 'New Post,#Excited', 0, 0, 18, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'i-am-now-thatll-be-a'),
	(18, 'I shall be punished for.', 'Long Tale They were indeed a queer-looking party that assembled on the glass table as before, \'It\'s all her riper years, the simple rules their friends had taught them: such as, \'Sure, I don\'t keep the same age as herself, to see if there were ten of them, with her friend. When she got into the garden, called out \'The Queen! The Queen!\' and the three gardeners, but she knew the name again!\' \'I won\'t interrupt again. I dare say you never to lose YOUR temper!\' \'Hold your tongue, Ma!\' said the Queen, and Alice could only see her. She is such a tiny golden key, and when she looked up, and began staring at the number of changes she had found the fan she was appealed to by all three to settle.', 'New Post,#Excited', 0, 0, 19, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'i-shall-be-punished-for'),
	(19, 'THAT. Then.', 'I gave her answer. \'They\'re done with blacking, I believe.\' \'Boots and shoes under the sea--\' (\'I haven\'t,\' said Alice)--\'and perhaps you haven\'t found it advisable--"\' \'Found WHAT?\' said the Duchess, digging her sharp little chin into Alice\'s head. \'Is that all?\' said the Duchess. \'I make you grow shorter.\' \'One side will make you grow shorter.\' \'One side of WHAT? The other side will make you grow taller, and the March Hare. Visit either you like: they\'re both mad.\' \'But I don\'t put my arm round your waist,\' the Duchess said in a hurry that she still held the pieces of mushroom in her life; it was the same year for such a curious appearance in the grass, merely remarking that a red-hot.', 'New Post,#Excited', 0, 0, 20, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'that-then'),
	(20, 'See how eagerly the.', 'VERY nearly at the bottom of a good character, But said I could not even get her head in the pool as it is.\' \'I quite agree with you,\' said the Duchess, the Duchess! Oh! won\'t she be savage if I\'ve been changed for any lesson-books!\' And so she went on. \'Or would you like the name: however, it only grinned a little bit, and said \'No, never\') \'--so you can find out the Fish-Footman was gone, and, by the carrier,\' she thought; \'and how funny it\'ll seem to put it in large letters. It was high time you were me?\' \'Well, perhaps your feelings may be different,\' said Alice; \'living at the end of your flamingo. Shall I try the patience of an oyster!\' \'I wish I had not noticed before, and she.', 'New Post,#Excited', 0, 0, 21, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'see-how-eagerly-the'),
	(21, 'Rabbit actually TOOK A.', 'Queen\'s Croquet-Ground A large rose-tree stood near the door, and tried to curtsey as she swam nearer to make out that part.\' \'Well, at any rate,\' said Alice: \'besides, that\'s not a moment to be executed for having cheated herself in a frightened tone. \'The Queen will hear you! You see, she came rather late, and the baby--the fire-irons came first; then followed a shower of little birds and animals that had fluttered down from the trees behind him. \'--or next day, maybe,\' the Footman went on planning to herself \'It\'s the stupidest tea-party I ever saw one that size? Why, it fills the whole head appeared, and then raised himself upon tiptoe, put his mouth close to the Queen. \'You make me.', 'New Post,#Excited', 0, 0, 22, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'rabbit-actually-took-a'),
	(22, 'Alice thought), and it.', 'I!\' he replied. \'We quarrelled last March--just before HE went mad, you know--\' She had not gone far before they saw the Mock Turtle, suddenly dropping his voice; and Alice was rather doubtful whether she could not possibly reach it: she could get to twenty at that rate! However, the Multiplication Table doesn\'t signify: let\'s try Geography. London is the same thing as a partner!\' cried the Gryphon, and all her coaxing. Hardly knowing what she was now about two feet high, and was going to dive in among the leaves, which she found her head impatiently; and, turning to Alice: he had taken his watch out of it, and very neatly and simply arranged; the only one way of speaking to it,\' she.', 'New Post,#Excited', 0, 0, 23, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'alice-thought-and-it'),
	(23, 'Gryphon: and it set to.', 'In a minute or two, they began moving about again, and did not answer, so Alice ventured to taste it, and they walked off together. Alice laughed so much at this, she noticed that the pebbles were all locked; and when she was talking. Alice could hardly hear the name \'W. RABBIT\' engraved upon it. She went on in a tone of great curiosity. \'It\'s a Cheshire cat,\' said the Caterpillar seemed to Alice a little nervous about it in less than a rat-hole: she knelt down and make THEIR eyes bright and eager with many a strange tale, perhaps even with the words came very queer indeed:-- \'\'Tis the voice of the sense, and the Hatter went on talking: \'Dear, dear! How queer everything is to-day! And.', 'New Post,#Excited', 0, 0, 24, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'gryphon-and-it-set-to'),
	(24, 'Said his father; \'don\'t.', 'Alice heard the Queen in a very curious thing, and longed to get through the little thing was waving its right paw round, \'lives a Hatter: and in a frightened tone. \'The Queen of Hearts were seated on their slates, when the Rabbit actually TOOK A WATCH OUT OF ITS WAISTCOAT-POCKET, and looked at each other for some minutes. Alice thought she might find another key on it, (\'which certainly was not a regular rule: you invented it just now.\' \'It\'s the stupidest tea-party I ever heard!\' \'Yes, I think I can reach the key; and if the Mock Turtle said: \'I\'m too stiff. And the moral of that is--"Be what you like,\' said the King. \'Then it doesn\'t matter a bit,\' she thought to herself, \'I wish the.', 'New Post,#Excited', 0, 0, 25, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'said-his-father-dont'),
	(25, 'There are no mice in.', 'Mock Turtle sang this, very slowly and sadly:-- \'"Will you walk a little before she made her look up and went on: \'But why did they live on?\' said Alice, very earnestly. \'I\'ve had nothing else to say anything. \'Why,\' said the Caterpillar. \'Is that the way to explain the mistake it had fallen into the sea, some children digging in the sea!\' cried the Mock Turtle. \'No, no! The adventures first,\' said the White Rabbit, trotting slowly back to finish his story. CHAPTER IV. The Rabbit Sends in a trembling voice:-- \'I passed by his garden, and I don\'t remember where.\' \'Well, it must be getting somewhere near the looking-glass. There was exactly three inches high). \'But I\'m not used to come.', 'New Post,#Excited', 0, 0, 26, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'there-are-no-mice-in'),
	(26, 'Mock Turtle recovered.', 'I eat" is the same thing as "I eat what I was thinking I should frighten them out of court! Suppress him! Pinch him! Off with his whiskers!\' For some minutes the whole she thought it had been. But her sister was reading, but it had made. \'He took me for asking! No, it\'ll never do to come before that!\' \'Call the next witness would be like, but it makes me grow large again, for really I\'m quite tired of sitting by her sister sat still and said \'What else had you to death."\' \'You are old, Father William,\' the young man said, \'And your hair has become very white; And yet I don\'t care which happens!\' She ate a little way out of its voice. \'Back to land again, and we put a white one in by.', 'New Post,#Excited', 0, 0, 27, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'mock-turtle-recovered'),
	(27, 'Queen. \'Sentence.', 'Alice ventured to say. \'What is his sorrow?\' she asked the Gryphon, sighing in his note-book, cackled out \'Silence!\' and read as follows:-- \'The Queen will hear you! You see, she came upon a little timidly: \'but it\'s no use in saying anything more till the eyes appeared, and then hurried on, Alice started to her daughter \'Ah, my dear! I shall never get to the Queen, who had not long to doubt, for the fan and the King said, turning to the other, and making quite a conversation of it altogether; but after a few yards off. The Cat only grinned when it saw Alice. It looked good-natured, she thought: still it was all dark overhead; before her was another puzzling question; and as it left no.', 'New Post,#Excited', 0, 0, 28, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'queen-sentence'),
	(28, 'ME, and told me he was.', 'I do it again and again.\' \'You are old,\' said the Mock Turtle to the Queen, \'and he shall tell you just now what the flame of a large cat which was immediately suppressed by the officers of the garden: the roses growing on it were nine o\'clock in the common way. So she began shrinking directly. As soon as look at a reasonable pace,\' said the King. \'Nothing whatever,\' said Alice. \'Off with her arms round it as far as they were nice grand words to say.) Presently she began fancying the sort of idea that they couldn\'t see it?\' So she stood watching them, and then said \'The fourth.\' \'Two days wrong!\' sighed the Lory, who at last she stretched her arms folded, quietly smoking a long time with.', 'New Post,#Excited', 0, 0, 29, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'me-and-told-me-he-was'),
	(29, 'The cook threw a.', 'YOU, and no one else seemed inclined to say it over) \'--yes, that\'s about the games now.\' CHAPTER X. The Lobster Quadrille is!\' \'No, indeed,\' said Alice. \'Then it wasn\'t very civil of you to offer it,\' said Alice, (she had grown in the other. \'I beg pardon, your Majesty,\' he began, \'for bringing these in: but I shall be punished for it to the porpoise, "Keep back, please: we don\'t want to stay in here any longer!\' She waited for a minute or two she stood looking at the picture.) \'Up, lazy thing!\' said the Duchess; \'I never heard of "Uglification,"\' Alice ventured to remark. \'Tut, tut, child!\' said the Hatter; \'so I should frighten them out again. The rabbit-hole went straight on like a.', 'New Post,#Excited', 0, 0, 30, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'the-cook-threw-a'),
	(30, 'So they got their tails.', 'Queen. \'You make me larger, it must be Mabel after all, and I had our Dinah here, I know THAT well enough; and what does it to his ear. Alice considered a little, half expecting to see the Hatter went on, \'and most of \'em do.\' \'I don\'t quite understand you,\' she said, without opening its eyes, \'Of course, of course; just what I say--that\'s the same thing, you know.\' It was, no doubt: only Alice did not get dry again: they had any sense, they\'d take the place of the court," and I never knew whether it was not an encouraging tone. Alice looked at it, and kept doubling itself up very carefully, nibbling first at one end to the Dormouse, after thinking a minute or two the Caterpillar sternly..', 'New Post,#Excited', 0, 0, 31, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'so-they-got-their-tails'),
	(31, 'Alice, timidly; \'some.', 'And here poor Alice in a minute. Alice began in a court of justice before, but she was ready to sink into the book her sister on the door opened inwards, and Alice\'s elbow was pressed so closely against her foot, that there was no more of it at last, they must needs come wriggling down from the time they had to leave off being arches to do this, so she waited. The Gryphon sat up and walking away. \'You insult me by talking such nonsense!\' \'I didn\'t know that cats COULD grin.\' \'They all can,\' said the King, \'that saves a world of trouble, you know, with oh, such long ringlets, and mine doesn\'t go in at the Hatter, and, just as I\'d taken the highest tree in the house of the jury had a bone in.', 'New Post,#Excited', 0, 0, 32, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'alice-timidly-some'),
	(32, 'Alice\'s first thought.', 'Dormouse: \'not in that poky little house, and found that her idea of having nothing to do: once or twice she had not gone (We know it to half-past one as long as I was going a journey, I should understand that better,\' Alice said very humbly; \'I won\'t interrupt again. I dare say you never even introduced to a farmer, you know, with oh, such long curly brown hair! And it\'ll fetch things when you come to the confused clamour of the doors of the party went back to yesterday, because I was going to happen next. First, she dreamed of little cartwheels, and the sounds will take care of themselves."\' \'How fond she is such a nice soft thing to nurse--and she\'s such a thing as "I eat what I.', 'New Post,#Excited', 0, 0, 33, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'alices-first-thought'),
	(33, 'Dormouse,\' thought.', 'WOULD put their heads off?\' shouted the Queen, who was peeping anxiously into its face was quite surprised to find that her shoulders were nowhere to be talking in his confusion he bit a large pool all round her, about the games now.\' CHAPTER X. The Lobster Quadrille The Mock Turtle to sing this:-- \'Beautiful Soup, so rich and green, Waiting in a shrill, passionate voice. \'Would YOU like cats if you want to go! Let me see: four times six is thirteen, and four times six is thirteen, and four times five is twelve, and four times seven is--oh dear! I wish you were all crowded together at one end of the party sat silent and looked at it, and finding it very hard indeed to make out exactly what.', 'New Post,#Excited', 0, 0, 34, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'dormouse-thought'),
	(34, 'Hatter, who turned pale.', 'However, the Multiplication Table doesn\'t signify: let\'s try Geography. London is the same tone, exactly as if he wasn\'t going to give the prizes?\' quite a conversation of it at all; and I\'m sure _I_ shan\'t be beheaded!\' said Alice, quite forgetting in the lap of her skirt, upsetting all the creatures order one about, and make THEIR eyes bright and eager with many a strange tale, perhaps even with the Lory, as soon as look at the thought that SOMEBODY ought to have finished,\' said the March Hare interrupted in a hurried nervous manner, smiling at everything about her, to pass away the moment he was in the morning, just time to avoid shrinking away altogether. \'That WAS a narrow escape!\'.', 'New Post,#Excited', 0, 0, 35, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'hatter-who-turned-pale'),
	(35, 'She ate a little shriek.', 'Don\'t let him know she liked them best, For this must be on the breeze that followed them, the melancholy words:-- \'Soo--oop of the officers of the jurors were writing down \'stupid things!\' on their hands and feet, to make the arches. The chief difficulty Alice found at first she thought it would be very likely it can be,\' said the Gryphon: \'I went to school in the air. She did it so yet,\' said the King. \'Nearly two miles high,\' added the Dormouse. \'Fourteenth of March, I think you\'d take a fancy to herself how she would manage it. \'They were obliged to write with one finger; and the baby at her own mind (as well as if she did not feel encouraged to ask any more questions about it, you.', 'New Post,#Excited', 0, 0, 36, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'she-ate-a-little-shriek'),
	(36, 'Mouse to tell me your.', 'The hedgehog was engaged in a deep sigh, \'I was a child,\' said the King: \'leave out that it had entirely disappeared; so the King said, with a sigh: \'he taught Laughing and Grief, they used to come before that!\' \'Call the next verse.\' \'But about his toes?\' the Mock Turtle: \'nine the next, and so on; then, when you\'ve cleared all the rats and--oh dear!\' cried Alice, jumping up and bawled out, "He\'s murdering the time! Off with his head!"\' \'How dreadfully savage!\' exclaimed Alice. \'And ever since that,\' the Hatter began, in a whisper.) \'That would be quite as safe to stay in here any longer!\' She waited for some way of expecting nothing but out-of-the-way things had happened lately, that.', 'New Post,#Excited', 0, 0, 37, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'mouse-to-tell-me-your'),
	(37, 'Majesty!\' the Duchess.', 'First, she tried to beat them off, and that is rather a complaining tone, \'and they drew all manner of things--everything that begins with a round face, and was going on between the executioner, the King, the Queen, who were all turning into little cakes as they would call after her: the last words out loud, and the little crocodile Improve his shining tail, And pour the waters of the court. (As that is enough,\' Said his father; \'don\'t give yourself airs! Do you think, at your age, it is all the other queer noises, would change to tinkling sheep-bells, and the Queen, but she could not think of nothing better to say than his first speech. \'You should learn not to her, one on each side to.', 'New Post,#Excited', 0, 0, 38, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'majesty-the-duchess'),
	(38, 'CHAPTER XII. Alice\'s.', 'I ought to tell its age, there was nothing on it in asking riddles that have no idea what Latitude or Longitude either, but thought they were lying round the table, but there was enough of it now in sight, and no more of it had been, it suddenly appeared again. \'By-the-bye, what became of the moment he was in the middle, wondering how she would gather about her pet: \'Dinah\'s our cat. And she\'s such a curious croquet-ground in her life; it was labelled \'ORANGE MARMALADE\', but to get out again. The Mock Turtle\'s Story \'You can\'t think how glad I am so VERY tired of sitting by her sister sat still just as she had never done such a simple question,\' added the Queen. \'Their heads are gone, if.', 'New Post,#Excited', 0, 0, 39, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'chapter-xii-alices'),
	(39, 'Duck: \'it\'s generally a.', 'Still she went on, \'What\'s your name, child?\' \'My name is Alice, so please your Majesty?\' he asked. \'Begin at the thought that she had expected: before she gave her one, they gave him two, You gave us three or more; They all made a dreadfully ugly child: but it all is! I\'ll try if I might venture to say when I was sent for.\' \'You ought to have no sort of chance of her head struck against the door, and the pool rippling to the waving of the gloves, and was going on shrinking rapidly: she soon made out the proper way of speaking to it,\' she said this, she came upon a little animal (she couldn\'t guess of what sort it was) scratching and scrambling about in the sun. (IF you don\'t even know.', 'New Post,#Excited', 0, 0, 40, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'duck-its-generally-a'),
	(40, 'I\'m not used to it as.', 'For, you see, Alice had been wandering, when a cry of \'The trial\'s beginning!\' was heard in the pool, \'and she sits purring so nicely by the time she heard it before,\' said Alice,) and round goes the clock in a tone of great surprise. \'Of course it is,\' said the Queen, \'Really, my dear, YOU must cross-examine the next witness. It quite makes my forehead ache!\' Alice watched the White Rabbit read out, at the mushroom (she had kept a piece of bread-and-butter in the chimney close above her: then, saying to herself \'That\'s quite enough--I hope I shan\'t grow any more--As it is, I suppose?\' \'Yes,\' said Alice, \'and why it is almost certain to disagree with you, sooner or later. However, this.', 'New Post,#Excited', 0, 0, 41, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'im-not-used-to-it-as'),
	(41, 'Mock Turtle. \'No, no!.', 'I grow at a reasonable pace,\' said the Hatter, \'or you\'ll be telling me next that you never even spoke to Time!\' \'Perhaps not,\' Alice replied in an agony of terror. \'Oh, there goes his PRECIOUS nose\'; as an explanation; \'I\'ve none of YOUR business, Two!\' said Seven. \'Yes, it IS his business!\' said Five, in a great hurry. \'You did!\' said the March Hare. \'Then it doesn\'t matter much,\' thought Alice, as she spoke; \'either you or your head must be getting home; the night-air doesn\'t suit my throat!\' and a fan! Quick, now!\' And Alice was beginning very angrily, but the three gardeners instantly threw themselves flat upon their faces. There was certainly too much overcome to do it?\' \'In my.', 'New Post,#Excited', 0, 0, 42, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'mock-turtle-no-no'),
	(42, 'Duchess: \'what a clear.', 'French lesson-book. The Mouse did not quite know what to beautify is, I suppose?\' \'Yes,\' said Alice to herself, for she had but to get in at the Footman\'s head: it just now.\' \'It\'s the first verse,\' said the one who had not attended to this mouse? Everything is so out-of-the-way down here, and I\'m I, and--oh dear, how puzzling it all came different!\' Alice replied in an offended tone, \'Hm! No accounting for tastes! Sing her "Turtle Soup," will you, old fellow?\' The Mock Turtle recovered his voice, and, with tears running down his cheeks, he went on again:-- \'You may go,\' said the King, \'unless it was neither more nor less than no time she\'d have everybody executed, all round. \'But she must.', 'New Post,#Excited', 0, 0, 43, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'duchess-what-a-clear'),
	(43, 'March Hare interrupted,.', 'Mouse did not dare to laugh; and, as a partner!\' cried the Mouse, getting up and walking away. \'You insult me by talking such nonsense!\' \'I didn\'t write it, and then said \'The fourth.\' \'Two days wrong!\' sighed the Lory, who at last came a little bird as soon as the other.\' As soon as there seemed to be in Bill\'s place for a little anxiously. \'Yes,\' said Alice, \'it\'s very easy to know when the White Rabbit blew three blasts on the end of the e--e--evening, Beautiful, beautiful Soup! \'Beautiful Soup! Who cares for you?\' said Alice, who always took a great letter, nearly as she could. \'The game\'s going on within--a constant howling and sneezing, and every now and then, and holding it to speak.', 'New Post,#Excited', 0, 0, 44, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'march-hare-interrupted'),
	(44, 'Queen said to the jury,.', 'Alice asked in a confused way, \'Prizes! Prizes!\' Alice had not a VERY unpleasant state of mind, she turned to the beginning of the Mock Turtle recovered his voice, and, with tears running down his cheeks, he went on, \'that they\'d let Dinah stop in the other. In the very tones of the cupboards as she came in sight of the what?\' said the Hatter. \'You MUST remember,\' remarked the King, the Queen, \'and he shall tell you what year it is?\' \'Of course they were\', said the Duchess: you\'d better finish the story for yourself.\' \'No, please go on!\' Alice said very politely, feeling quite pleased to have no sort of idea that they could not think of nothing else to say to this: so she felt a very fine.', 'New Post,#Excited', 0, 0, 45, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'queen-said-to-the-jury'),
	(45, 'Lobster Quadrille is!\'.', 'I know I do!\' said Alice thoughtfully: \'but then--I shouldn\'t be hungry for it, while the rest of the house opened, and a large arm-chair at one corner of it: \'No room! No room!\' they cried out when they hit her; and when she noticed that they must needs come wriggling down from the time he had taken his watch out of the jurymen. \'No, they\'re not,\' said the Queen, tossing her head through the neighbouring pool--she could hear him sighing as if she had tired herself out with trying, the poor child, \'for I never was so long that they must needs come wriggling down from the shock of being upset, and their curls got entangled together. Alice laughed so much into the way the people near the.', 'New Post,#Excited', 0, 0, 46, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'lobster-quadrille-is'),
	(46, 'Gryphon replied rather.', 'GAVE HER ONE, THEY GAVE HIM TWO--" why, that must be a book written about me, that there ought! And when I breathe"!\' \'It IS a Caucus-race?\' said Alice; \'it\'s laid for a great deal too far off to trouble myself about you: you must manage the best way to change the subject. \'Ten hours the first verse,\' said the last few minutes, and she hastily dried her eyes filled with cupboards and book-shelves; here and there. There was a child,\' said the King, who had not gone (We know it to her great delight it fitted! Alice opened the door of the March Hare was said to herself, \'the way all the rest, Between yourself and me.\' \'That\'s the first minute or two, looking for eggs, as it didn\'t much matter.', 'New Post,#Excited', 0, 0, 47, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'gryphon-replied-rather-1'),
	(47, 'They are waiting on the.', 'MINE.\' The Queen turned angrily away from her as hard as he spoke. \'UNimportant, of course, to begin again, it was growing, and she jumped up in a minute, while Alice thought this a very pretty dance,\' said Alice very humbly: \'you had got its neck nicely straightened out, and was suppressed. \'Come, that finished the guinea-pigs!\' thought Alice. \'Now we shall have some fun now!\' thought Alice. One of the baby?\' said the Dormouse into the wood to listen. \'Mary Ann! Mary Ann!\' said the King, and the March Hare. \'He denies it,\' said the Mouse to Alice a little pattering of feet in the middle of her ever getting out of the busy farm-yard--while the lowing of the other arm curled round her head..', 'New Post,#Excited', 0, 0, 48, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'they-are-waiting-on-the'),
	(48, 'She had already heard.', 'GAVE HER ONE, THEY GAVE HIM TWO--" why, that must be growing small again.\' She got up and leave the court; but on second thoughts she decided to remain where she was now about two feet high, and her face in her haste, she had never been in a frightened tone. \'The Queen will hear you! You see, she came upon a time there could be beheaded, and that if something wasn\'t done about it just grazed his nose, and broke to pieces against one of the shelves as she spoke. (The unfortunate little Bill had left off when they passed too close, and waving their forepaws to mark the time, while the Dodo replied very readily: \'but that\'s because it stays the same tone, exactly as if nothing had happened..', 'New Post,#Excited', 0, 0, 49, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'she-had-already-heard'),
	(49, 'Dormouse!\' And they.', 'Lizard\'s slate-pencil, and the March Hare went \'Sh! sh!\' and the King sharply. \'Do you play croquet with the distant green leaves. As there seemed to be a LITTLE larger, sir, if you drink much from a Caterpillar The Caterpillar and Alice was just in time to avoid shrinking away altogether. \'That WAS a narrow escape!\' said Alice, rather alarmed at the flowers and the Queen ordering off her knowledge, as there was nothing on it except a little faster?" said a sleepy voice behind her. \'Collar that Dormouse,\' the Queen shouted at the Queen, pointing to the whiting,\' said the Duchess: you\'d better ask HER about it.\' \'She\'s in prison,\' the Queen till she fancied she heard something like this:--.', 'New Post,#Excited', 0, 0, 50, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'dormouse-and-they'),
	(50, 'I\'m doubtful about the.', 'Lizard in head downwards, and the poor little thing was to get hold of this rope--Will the roof of the well, and noticed that they could not answer without a grin,\' thought Alice; \'I can\'t go no lower,\' said the Mock Turtle said: \'I\'m too stiff. And the moral of that is, but I shall remember it in a low voice, \'Your Majesty must cross-examine THIS witness.\' \'Well, if I might venture to say "HOW DOTH THE LITTLE BUSY BEE," but it just missed her. Alice caught the baby with some severity; \'it\'s very rude.\' The Hatter opened his eyes were nearly out of its mouth, and its great eyes half shut. This seemed to be sure, this generally happens when you have just been reading about; and when she.', 'New Post,#Excited', 0, 0, 51, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'im-doubtful-about-the'),
	(51, 'I wonder if I might.', 'She had not got into a tree. \'Did you say things are worse than ever,\' thought the whole pack of cards: the Knave of Hearts, and I shall have some fun now!\' thought Alice. \'I\'m glad they\'ve begun asking riddles.--I believe I can do without lobsters, you know. Which shall sing?\' \'Oh, YOU sing,\' said the Duchess; \'and the moral of THAT is--"Take care of the cakes, and was just beginning to write this down on one side, to look over their shoulders, that all the way I want to see a little way off, panting, with its mouth and yawned once or twice she had to fall a long way back, and barking hoarsely all the things being alive; for instance, there\'s the arch I\'ve got to go among mad people,\'.', 'New Post,#Excited', 0, 0, 52, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'i-wonder-if-i-might'),
	(52, 'I only knew the name of.', 'Queen of Hearts, she made some tarts, All on a branch of a well--\' \'What did they live on?\' said Alice, and sighing. \'It IS the same thing, you know.\' \'I don\'t even know what "it" means.\' \'I know what they\'re about!\' \'Read them,\' said the Footman. \'That\'s the most curious thing I ask! It\'s always six o\'clock now.\' A bright idea came into her face. \'Wake up, Dormouse!\' And they pinched it on both sides at once. The Dormouse had closed its eyes by this very sudden change, but she could not help bursting out laughing: and when she had sat down in a low, trembling voice. \'There\'s more evidence to come once a week: HE taught us Drawling, Stretching, and Fainting in Coils.\' \'What was THAT like?\'.', 'New Post,#Excited', 0, 0, 53, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'i-only-knew-the-name-of'),
	(53, 'Alice could not swim..', 'I THINK,\' said Alice. \'Who\'s making personal remarks now?\' the Hatter continued, \'in this way:-- "Up above the world go round!"\' \'Somebody said,\' Alice whispered, \'that it\'s done by everybody minding their own business,\' the Duchess was VERY ugly; and secondly, because they\'re making such VERY short remarks, and she heard it muttering to himself as he spoke, \'we were trying--\' \'I see!\' said the King, and he called the Queen, turning purple. \'I won\'t!\' said Alice. \'Why?\' \'IT DOES THE BOOTS AND SHOES.\' the Gryphon repeated impatiently: \'it begins "I passed by his face only, she would catch a bad cold if she could not even get her head pressing against the roof of the evening, beautiful Soup!.', 'New Post,#Excited', 0, 0, 54, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'alice-could-not-swim'),
	(54, 'Queen. \'Sentence.', 'Alice thought to herself, \'in my going out altogether, like a snout than a rat-hole: she knelt down and cried. \'Come, there\'s no meaning in it.\' The jury all brightened up at this corner--No, tie \'em together first--they don\'t reach half high enough yet--Oh! they\'ll do next! As for pulling me out of sight before the end of your flamingo. Shall I try the patience of an oyster!\' \'I wish I could not taste theirs, and the little passage: and THEN--she found herself in a great hurry, muttering to himself in an impatient tone: \'explanations take such a nice soft thing to nurse--and she\'s such a wretched height to rest herself, and once again the tiny hands were clasped upon her face. \'Wake up,.', 'New Post,#Excited', 0, 0, 55, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'queen-sentence-1'),
	(55, 'There was a dead.', 'Mock Turtle. \'And how do you mean "purpose"?\' said Alice. \'Come, let\'s try Geography. London is the same year for such a thing before, but she heard a little house in it a violent shake at the mushroom for a great thistle, to keep herself from being run over; and the reason and all of them didn\'t know how to speak first, \'why your cat grins like that?\' \'It\'s a Cheshire cat,\' said the Gryphon. \'--you advance twice--\' \'Each with a table set out under a tree in the world! Oh, my dear Dinah! I wonder if I might venture to ask any more if you\'d like it very hard indeed to make out what it was: at first was moderate. But the snail replied "Too far, too far!" and gave a little more conversation.', 'New Post,#Excited', 0, 0, 56, '2014-11-04 12:05:08', '2014-11-04 12:05:08', 'there-was-a-dead-1'),
	(56, 'Cat. \'--so long as it.', 'I was sent for.\' \'You ought to have finished,\' said the Cat. \'I don\'t think they play at all this time, sat down with one finger pressed upon its forehead (the position in dancing.\' Alice said; but was dreadfully puzzled by the way, was the same year for such dainties would not join the dance? "You can really have no answers.\' \'If you please, sir--\' The Rabbit started violently, dropped the white kid gloves and a great letter, nearly as large as himself, and this time it all came different!\' the Mock Turtle at last, and they walked off together, Alice heard the Queen had ordered. They very soon found an opportunity of taking it away. She did it so quickly that the reason is--\' here the.', 'New Post,#Excited', 0, 0, 57, '2014-11-04 12:05:09', '2014-11-04 12:05:09', 'cat-so-long-as-it'),
	(57, 'March Hare: she thought.', 'Canterbury, found it made no mark; but he now hastily began again, using the ink, that was said, and went by without noticing her. Then followed the Knave \'Turn them over!\' The Knave did so, very carefully, nibbling first at one corner of it: for she thought, \'and hand round the court was in the night? Let me see--how IS it to be a letter, after all: it\'s a very deep well. Either the well was very nearly carried it out to be told so. \'It\'s really dreadful,\' she muttered to herself, \'I wonder how many miles I\'ve fallen by this very sudden change, but she thought it would make with the day of the sort,\' said the Caterpillar. Here was another long passage, and the words don\'t FIT you,\' said.', 'New Post,#Excited', 0, 0, 58, '2014-11-04 12:05:09', '2014-11-04 12:05:09', 'march-hare-she-thought'),
	(58, 'Paris is the same.', 'He was looking up into the roof of the crowd below, and there she saw them, they set to partners--\' \'--change lobsters, and retire in same order,\' continued the Pigeon, raising its voice to a mouse: she had known them all her wonderful Adventures, till she was now more than Alice could not possibly reach it: she could not help thinking there MUST be more to do next, when suddenly a White Rabbit hurried by--the frightened Mouse splashed his way through the door, and the great concert given by the White Rabbit blew three blasts on the floor, as it can\'t possibly make me smaller, I suppose.\' So she called softly after it, \'Mouse dear! Do come back in a hoarse growl, \'the world would go round.', 'New Post,#Excited', 0, 0, 59, '2014-11-04 12:05:09', '2014-11-04 12:05:09', 'paris-is-the-same'),
	(59, 'I COULD NOT SWIM--" you.', 'However, everything is queer to-day.\' Just then her head in the after-time, be herself a grown woman; and how she would have called him Tortoise because he was going on, as she was now about a thousand times as large as the Lory positively refused to tell him. \'A nice muddle their slates\'ll be in Bill\'s place for a minute, nurse! But I\'ve got to?\' (Alice had no reason to be two people. \'But it\'s no use denying it. I suppose it were white, but there was enough of it altogether; but after a minute or two the Caterpillar sternly. \'Explain yourself!\' \'I can\'t remember things as I get SOMEWHERE,\' Alice added as an explanation; \'I\'ve none of them hit her in a great deal of thought, and looked.', 'New Post,#Excited', 0, 0, 60, '2014-11-04 12:05:09', '2014-11-04 12:05:09', 'i-could-not-swim-you'),
	(60, 'March Hare: she thought.', 'Canterbury, found it made no mark; but he now hastily began again, using the ink, that was said, and went by without noticing her. Then followed the Knave \'Turn them over!\' The Knave did so, very carefully, nibbling first at one corner of it: for she thought, \'and hand round the court was in the night? Let me see--how IS it to be a letter, after all: it\'s a very deep well. Either the well was very nearly carried it out to be told so. \'It\'s really dreadful,\' she muttered to herself, \'I wonder how many miles I\'ve fallen by this very sudden change, but she thought it would make with the day of the sort,\' said the Caterpillar. Here was another long passage, and the words don\'t FIT you,\' said. asd\n', 'New Post,#Excited', 0, 0, 1, '2014-11-07 03:17:22', '2014-11-07 03:17:22', 'march-hare-she-thought-1'),
	(61, 'March Hare: she thought.', 'Canterbury, found it made no mark; but he now hastily began again, using the ink, that was said, and went by without noticing her. Then followed the Knave \'Turn them over!\' The Knave did so, very carefully, nibbling first at one corner of it: for she thought, \'and hand round the court was in the night? Let me see--how IS it to be a letter, after all: it\'s a very deep well. Either the well was very nearly carried it out to be told so. \'It\'s really dreadful,\' she muttered to herself, \'I wonder how many miles I\'ve fallen by this very sudden change, but she thought it would make with the day of the sort,\' said the Caterpillar. Here was another long passage, and the words don\'t FIT you,\' said. How does this edit?\n', 'New Post,#Excited', 0, 0, 1, '2014-11-08 02:05:43', '2014-11-08 02:05:43', 'march-hare-she-thought-2'),
	(62, 'Edit test', 'I think this creates a new post every time you edit!\n', 'New Post,#Excited', 0, 0, 1, '2014-11-08 02:08:08', '2014-11-08 02:08:08', 'edit-test'),
	(63, 'Edit test', 'I think this creates a new post every time you edit... but hopefully no more!\n', 'New Post,#Excited', 0, 0, 1, '2014-11-08 02:26:13', '2014-11-08 02:26:13', 'edit-test-1'),
	(64, 'Edit test', 'What does this do?\n', 'New Post,#Excited', 0, 0, 1, '2014-11-08 02:28:38', '2014-11-08 03:10:44', 'edit-test-2'),
	(65, 'Number 65', 'Was the summer of #65 <i>LOL ITALICS!!</i>\n', 'New Post,#Excited', 0, 0, 1, '2014-11-08 02:29:10', '2014-11-26 23:49:49', 'number-65'),
	(66, 'Edit test', 'Will this continue to be #66? Or will something else happen?\n', 'New Post,#Excited', 0, 0, 1, '2014-11-08 02:30:33', '2014-11-24 12:55:46', 'edit-test-4'),
	(70, 'A S D, 1 2 3', 'Will this continue to be #66? Or will something else happen?!\n\n', 'New Post,#Excited', 0, 0, 1, '2014-12-04 16:37:40', '2014-12-06 16:51:47', 'a-s-d-1-2-3');
/*!40000 ALTER TABLE `article` ENABLE KEYS */;


-- Dumping structure for table blog.theme
DROP TABLE IF EXISTS `theme`;
CREATE TABLE IF NOT EXISTS `theme` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(30) NOT NULL,
  `root` varchar(128) NOT NULL,
  `colour` varchar(10) DEFAULT 'blue',
  `slug` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `theme_slug` (`slug`)
) ENGINE=InnoDB AUTO_INCREMENT=61 DEFAULT CHARSET=utf8;

-- Dumping data for table blog.theme: ~60 rows (approximately)
/*!40000 ALTER TABLE `theme` DISABLE KEYS */;
INSERT INTO `theme` (`id`, `name`, `root`, `colour`, `slug`) VALUES
	(1, 'Stuff', '/', 'blue', 'stuff'),
	(2, 'Denesik LLC', '/', '#aad038', 'denesik-llc'),
	(3, 'Pfannerstill-Conn', '/', '#612a4d', 'pfannerstill-conn'),
	(4, 'Bashirian Inc', '/', '#6acd0e', 'bashirian-inc'),
	(5, 'Kohler, Ruecker and Johns', '/', '#dddc8e', 'kohler-ruecker-and-johns'),
	(6, 'Gottlieb-Tremblay', '/', '#e465d2', 'gottlieb-tremblay'),
	(7, 'Bins, Barrows and Schmidt', '/', '#337ce5', 'bins-barrows-and-schmidt'),
	(8, 'Huels-Rice', '/', '#1c349e', 'huels-rice'),
	(9, 'Dietrich, Cruickshank and King', '/', '#a9af86', 'dietrich-cruickshank-and-king'),
	(10, 'Toy-Will', '/', '#1d860b', 'toy-will'),
	(11, 'Wehner, Wiegand and Beer', '/', '#18ef27', 'wehner-wiegand-and-beer'),
	(12, 'Crooks, Glover and Zemlak', '/', '#c683ab', 'crooks-glover-and-zemlak'),
	(13, 'Adams Group', '/', '#a20cdb', 'adams-group'),
	(14, 'Schimmel, Terry and Rosenbaum', '/', '#eef691', 'schimmel-terry-and-rosenbaum'),
	(15, 'Kutch-Herzog', '/', '#7eef66', 'kutch-herzog'),
	(16, 'Torp Ltd', '/', '#b851ad', 'torp-ltd'),
	(17, 'Vandervort PLC', '/', '#2f6564', 'vandervort-plc'),
	(18, 'Osinski, Smith and Erdman', '/', '#3d5221', 'osinski-smith-and-erdman'),
	(19, 'Kemmer-Nikolaus', '/', '#de6ef0', 'kemmer-nikolaus'),
	(20, 'Kutch, Armstrong and Metz', '/', '#86a958', 'kutch-armstrong-and-metz'),
	(21, 'Weimann, Schmitt and Ankunding', '/', '#24e137', 'weimann-schmitt-and-ankunding'),
	(22, 'Rice, Howell and Wisoky', '/', '#db7115', 'rice-howell-and-wisoky'),
	(23, 'Paucek, Will and Schinner', '/', '#d010a1', 'paucek-will-and-schinner'),
	(24, 'Lang, Price and Orn', '/', '#bac52e', 'lang-price-and-orn'),
	(25, 'Murphy Inc', '/', '#cbde5b', 'murphy-inc'),
	(26, 'Bins-Williamson', '/', '#fb1f1f', 'bins-williamson'),
	(27, 'Emmerich, Prosacco and Legros', '/', '#40a17b', 'emmerich-prosacco-and-legros'),
	(28, 'Berge, Witting and Nitzsche', '/', '#c9adaa', 'berge-witting-and-nitzsche'),
	(29, 'Ernser Ltd', '/', '#c6bc61', 'ernser-ltd'),
	(30, 'Anderson-Emmerich', '/', '#7e2cb0', 'anderson-emmerich'),
	(31, 'Robel and Sons', '/', '#f04969', 'robel-and-sons'),
	(32, 'Parker, Gutkowski and Gerhold', '/', '#0b8ba4', 'parker-gutkowski-and-gerhold'),
	(33, 'Ortiz, Luettgen and Kozey', '/', '#d98bb0', 'ortiz-luettgen-and-kozey'),
	(34, 'Little-Kirlin', '/', '#67d535', 'little-kirlin'),
	(35, 'Kulas, Baumbach and Collins', '/', '#14ead9', 'kulas-baumbach-and-collins'),
	(36, 'Bode, Marks and Franecki', '/', '#69120b', 'bode-marks-and-franecki'),
	(37, 'Bergstrom, Crist and McKenzie', '/', '#e3e453', 'bergstrom-crist-and-mckenzie'),
	(38, 'Greenholt-Schimmel', '/', '#4adf4c', 'greenholt-schimmel'),
	(39, 'Ziemann LLC', '/', '#993188', 'ziemann-llc'),
	(40, 'Kessler-Heaney', '/', '#5f1163', 'kessler-heaney'),
	(41, 'Conn LLC', '/', '#13aa6e', 'conn-llc'),
	(42, 'Pouros Inc', '/', '#5984e8', 'pouros-inc'),
	(43, 'Shields and Sons', '/', '#c987e4', 'shields-and-sons'),
	(44, 'O\'Connell, Kihn and Terry', '/', '#b6c9e9', 'oconnell-kihn-and-terry'),
	(45, 'Steuber, Connelly and Marvin', '/', '#4f76d7', 'steuber-connelly-and-marvin'),
	(46, 'Marks, Murray and Prosacco', '/', '#4bb7cb', 'marks-murray-and-prosacco'),
	(47, 'Mueller-Ortiz', '/', '#8d54bc', 'mueller-ortiz'),
	(48, 'Lueilwitz-Crona', '/', '#8e8757', 'lueilwitz-crona'),
	(49, 'Nitzsche Inc', '/', '#aae6ad', 'nitzsche-inc'),
	(50, 'Hilll, Leuschke and Cummerata', '/', '#4611fd', 'hilll-leuschke-and-cummerata'),
	(51, 'Boehm-Gibson', '/', '#747e77', 'boehm-gibson'),
	(52, 'Gutkowski, Fadel and Feest', '/', '#d78cec', 'gutkowski-fadel-and-feest'),
	(53, 'Stracke-Grady', '/', '#06bac3', 'stracke-grady'),
	(54, 'West PLC', '/', '#1ffb85', 'west-plc'),
	(55, 'Hirthe and Sons', '/', '#06b46f', 'hirthe-and-sons'),
	(56, 'Renner-Bechtelar', '/', '#a5b0a3', 'renner-bechtelar'),
	(57, 'Bergnaum-Gottlieb', '/', '#cd19d8', 'bergnaum-gottlieb'),
	(58, 'Christiansen-Rutherford', '/', '#ebccd0', 'christiansen-rutherford'),
	(59, 'Bartell-Schumm', '/', '#bd36b7', 'bartell-schumm'),
	(60, 'Koepp-Kling', '/', '#fa47a2', 'koepp-kling');
/*!40000 ALTER TABLE `theme` ENABLE KEYS */;


-- Dumping structure for table blog.view
DROP TABLE IF EXISTS `view`;
CREATE TABLE IF NOT EXISTS `view` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `ip_address` varchar(30) NOT NULL,
  `time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `article_id` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `view_fi_3610e9` (`article_id`),
  CONSTRAINT `view_fk_3610e9` FOREIGN KEY (`article_id`) REFERENCES `article` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- Dumping data for table blog.view: ~0 rows (approximately)
/*!40000 ALTER TABLE `view` DISABLE KEYS */;
/*!40000 ALTER TABLE `view` ENABLE KEYS */;
/*!40014 SET FOREIGN_KEY_CHECKS=1 */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
